import ReferalAside from '@/components/ReferalAside'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function ReferalLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className='px-2xl flex w-full justify-between gap-5'>
			{children}
			<ReferalAside />
		</div>
	)
}
