import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from '@/components/Header'
import '../globals.css'

const iranYekan = localFont({
	src: [
		{ path: '../../public/font/IRANYekanWebLight.woff2', weight: '300', style: 'normal' },
		{ path: '../../public/font/IRANYekanWebRegular.woff2', weight: '400', style: 'normal' },
		{ path: '../../public/font/IRANYekanWebMedium.woff2', weight: '500', style: 'normal' },
		{ path: '../../public/font/IRANYekanWebBold.woff2', weight: '700', style: 'normal' },
	],
})

export const metadata: Metadata = {
	title: 'دیجیکالا مهر',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='fa' dir='rtl'>
			<body className={`${iranYekan.className}`}>
				<div className='flex flex-col justify-between'>
					<Header />
					<main className='mt-xl w-full'>{children}</main>
				</div>
			</body>
		</html>
	)
}
